### ISSUE TITLE
terminating with uncaught exception of type St9bad_alloc: std::bad_alloc" failed

### ISSUE THREAD

**Issue by ellu15** [pedroSG94/vlc-example-streamplayer#12]
Hii,
RTMP video playing is stop after some time and I get following error and after app close.
And i uses Nexus 5(Marshmallow 6.0.1) for testing.

>A/libc: /usr/local/google/buildbot/src/android/ndk-r14-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type St9bad_alloc: std::bad_alloc" failed

**Comment by pedroSG94** [comment]
This look a VLC bug. I can't do anything report it to VLC team:
https://code.videolan.org/videolan/vlc-android

**Comment by ellu15** [comment]
Thank You.
