### ISSUE TITLE
Recording Video

### ISSUE THREAD

**Issue by linng85** [pedroSG94/vlc-example-streamplayer#2]
Hi, 
Thanks a lot for the project. The code is working. What should i do if i want to record the video? Thanks a lot.

**Comment by pedroSG94** [comment]
Record video and audio is no available in VLC for Android. You can capture video if you use a mediacodec inputsurface to render with VLC but for audio you will need modify VLC and this is difficult :(

**Comment by linng85** [comment]
Ok. Thanks a lot!
