### ISSUE TITLE
Is there the ability to add video and screenshots

### ISSUE THREAD

**Issue by ILoveLin** [pedroSG94/vlc-example-streamplayer#45]
Can I add video screenshots and video recording？

**Comment by ILoveLin** [comment]
Can you see if you can add these two functions

**Comment by pedroSG94** [comment]
Hello,

This proyect is an example to use VLC in order to get stream in an easy way.
I have no idea to add new features or give support for now

**Comment by ILoveLin** [comment]
thanks
